substitutions:
  name: m5stack-atom3echo
  friendly_name: atom3echo
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: atom3echo
  #comment: M5Echo Hey,Jarvis
api:
  encryption:
    key: A+5Bc5Je9gdx5sgloAt+Wt2FckEfp4FPxvQqWwM6MMk=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


