esphome:
  name: az32d05
  friendly_name: az32d05

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "3msmphzIw/ZRAXg41P45pWWqjeaH8TKKQjVJE6j6ofo="

ota:
  password: "e05e2d52cc9f9b41644c35c001e7d953"

wifi:
  ssid: 7wlan # !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: none
#  reboot_timeout: 0s
#  domain: ".local"       #  domain  .fritz.box 
#  output_power: 20dB
#  fast_connect: true

#  manual_ip:
#    static_ip: 192.168.1.170 # 3EG5-Garten (A) = Bereich ,  d1 unter test 1 lcd1602 time+ date over ha
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0 # subnet2 test 255.255.0.0
#    dns1: 192.168.1.1
#    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Az32D05 Fallback Hotspot"
    password: "j1sSCqK4M6WX"

captive_portal:

# https://github.com/schmurtzm/MrDiy-Audio-Notifier/blob/10ea2294db9181ba6b0cc6df2d6ee75b05082151/src/main.cpp#L107
# Example configuration entry
#______    _____   _____    ____    ___  
#|  ____|  / ____| |  __ \  |___ \  |__ \ 
#| |__    | (___   | |__) |   __) |    ) |
#|  __|    \___ \  |  ___/   |__ <    / / 
#| |____   ____) | | |       ___) |  / /_ 
#|______| |_____/  |_|      |____/  |____|
#
#+-----------------+-----------------+--------------+--------------------+
#|   audio pins    |  External DAC   | Internal DAC |       No DAC       |
#+-----------------+-----------------+--------------+--------------------+
#| DAC - LCK(LRC)  | GPIO25          | NA           | NA                 | Green = LCK
#| DAC - BCK(BCLK) | GPIO26          | NA           | NA                 | Blue = BCK
#| DAC - I2So(DIN) | GPIO22          | NA           | NA                 | Yellow = DIN
#| speaker L       | NA (on the DAC) | GPIO25       | GPIO22 (L&R mixed) | L+ and L- = speaker 8ohm 2W
#| speaker R       | NA (on the DAC) | GPIO26       | GPIO22 (L&R mixed) |
#+-----------------+-----------------+--------------+--------------------+

#VCC 5V
#GND GND

i2s_audio:
  i2s_lrclk_pin: GPIO25 #33
  i2s_bclk_pin: GPIO26 #19

media_player:
  - platform: i2s_audio
    name: ESPHome I2S Media Player
    dac_type: external
    i2s_dout_pin: GPIO22 # din 22
    mode: mono #stereo