esphome:
  name: az32d02
  friendly_name: az32d02

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "oApN5S7O/x+HCAktb1XE/pvrEDl6OYeUNwGWiIXrq50="

ota:
  password: "31ff032ca824169f32e7b137dd43f299"

wifi:
  ssid: 7wlan # !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: none
#  reboot_timeout: 0s
#  #domain: ".fritz.box"
#  output_power: 20dB
#  fast_connect: true

#  manual_ip:
#    static_ip: 192.168.1.167 # 3EG5-Garten (A) = Bereich ,  d2 unter test 1 lcd1602 time+ date over ha
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0 # subnet2 test 255.255.0.0
#    dns1: 192.168.1.1
#    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Az32D02 Fallback Hotspot"
    password: "oU9mIaLSJkye"

captive_portal:

i2c: #(0x27,16,2) lcd1602 PCF8574T, 1=GND, 2=+5V, 3=SDA(orange)auf PIN13, 4=SCL(gelb)auf PIN14  (!PIN12 strapping pin not used)
  sda: GPIO21  #32
  scl: GPIO22  #33
  frequency: 400kHz # fix warnings

time:
  - platform: homeassistant
    id: my_time

display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x27
    update_interval: 1s  # 1s - 10s
    id: lcd
    lambda: |-
      it.strftime(0, 0, "Time %H:%M:%S", id(my_time).now());
      it.strftime(0, 1, "Date %d.%m.%Y", id(my_time).now()); 

    