esphome:
  name: az32e07
  friendly_name: az32e07

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "tQWvuYxHOSbUmZcoXTtrr9/NsZ1j7YlKuhnAT4/KlXU="

ota:
  password: "da1d781f652a3b4f22edfd5a9671748e"

wifi:
  ssid: 6wlan # !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Az32E07 Fallback Hotspot"
    password: "Ank01AtoBnDL"

captive_portal:

i2c: #(0x27,16,2) lcd1602 PCF8574T, 1=GND, 2=+5V, 3=SDA(orange)auf PIN13, 4=SCL(gelb)auf PIN14  (!PIN12 strapping pin not used)
  sda: GPIO21  #32
  scl: GPIO22  #33
  # frequency: 400kHz # fix warnings

time:
  - platform: homeassistant
    id: my_time

sensor:
  - platform: homeassistant
    id: speedtestdownload
    entity_id: sensor.speedtest_download
    internal: true
  - platform: homeassistant
    id: speedtestupload
    entity_id: sensor.speedtest_upload
    internal: true

display:
  - platform: lcd_pcf8574
    dimensions: 20x4
    address: 0x27
    update_interval: 1s  # 1s - 10s "Mbps");
    id: lcd
    lambda: |-
      it.strftime(0, 0, "Time: %H:%M:%S", id(my_time).now());
      it.strftime(0, 1, "Date: %d.%m.%Y", id(my_time).now());
      it.printf(0, 2, "Download: %2.1f", id(speedtestdownload).state);
      it.printf(0, 3, "Upload^^: %2.1f", id(speedtestupload).state);
    