substitutions:
  name: m5stack-atom-echo-30d6dc
  friendly_name: Atom Echo 30d6dc
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: E9M85W5AiKm1dIBkyZRcaJdfvaTm/KJwBZo+ejpwQNo=


wifi:
  ssid: 6wlan # !secret wifi_ssid
  password: !secret wifi_password
